[package]
name = "xxh3"
version = "0.1.0"
authors = []
edition = "2018"

[lib]
name = "xxh3"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.22.2"
xxhash-rust = { version = "0.8.2", features = ["xxh3"] }
