name: default

on:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Elixir
        uses: erlef/setup-elixir@v1
        with:
          elixir-version: "1.12.3"
          otp-version: "24.1.4"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-

      - name: Install dependencies
        run: mix deps.get

      - name: Check formatted
        run: mix format --check-formatted

      - name: Compile (warnings as errors)
        run: MIX_ENV=bench mix compile --warnings-as-errors

      - name: Run benchmarks
        run: MIX_ENV=bench mix run bench/hashing.exs
